name: Backend CI Build

on:
  push:
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend-build.yml'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: vars
        run: |
          echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/shaik-backend:${IMAGE_TAG} \
          ./apps/backend

      - name: Push Image
        run: |
          docker push \
          ${{ secrets.DOCKERHUB_USERNAME }}/shaik-backend:${IMAGE_TAG}

      - name: Update Kubernetes Manifest (GitOps step)
        run: |
          sed -i "s|image: .*shaik-backend.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/shaik-backend:${IMAGE_TAG}|g" infra/k8s/backend/backend.yaml

      - name: Commit Manifest Change
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add infra/k8s/backend/backend.yaml
          git commit -m "update backend image to ${IMAGE_TAG}" || echo "no changes"
          git push