name: Build Backend Image

on:
  push:
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/shaik-backend:latest \
          ./apps/backend

      - name: Push Image
        run: |
          docker push \
          ${{ secrets.DOCKERHUB_USERNAME }}/shaik-backend:latest

      # ✅ NEW STEP ADDED (CI/CD → K8s SYNC)
      - name: Trigger Kubernetes Rollout
        run: |
          kubectl rollout restart deployment backend-api -n backend