name: Build Backend Image

on:
  push:
    paths:
      - 'apps/backend/**'
      - '.github/workflows/backend-build.yml'

jobs:
  build:
    runs-on: self-hosted

    steps:
      # -----------------------------
      # 1. Checkout Source Code
      # -----------------------------
      - name: Checkout Code
        uses: actions/checkout@v4

      # -----------------------------
      # 2. Login to Docker Hub
      # -----------------------------
      - name: Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -----------------------------
      # 3. Build Docker Image
      # -----------------------------
      - name: Build Image
        run: |
          docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/shaik-backend:latest \
          ./apps/backend

      # -----------------------------
      # 4. Push Docker Image
      # -----------------------------
      - name: Push Image
        run: |
          docker push \
          ${{ secrets.DOCKERHUB_USERNAME }}/shaik-backend:latest

      # -----------------------------
      # 5. Deploy to Kubernetes
      # -----------------------------
      - name: Deploy Backend to Kubernetes
        run: |
          kubectl apply -f infra/k8s/backend/

      # -----------------------------
      # 6. Wait for Rollout (CRITICAL)
      # -----------------------------
      - name: Wait for Rollout to Complete
        run: |
          kubectl rollout status deployment/backend-api -n backend --timeout=120s

      # -----------------------------
      # 7. Verify Deployment Health
      # -----------------------------
      - name: Verify Backend Health
        run: |
          kubectl get pods -n backend
          kubectl get svc -n backend
          kubectl describe deployment backend-api -n backend